name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub pietrolesci
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://pietrolesci:$HF_TOKEN@huggingface.co/spaces/pietrolesci/wordify main
      - name: Push to hub MilaNLProc
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_MILANLPROC }}
        run: git push https://MilaNLProc:$HF_TOKEN@huggingface.co/spaces/MilaNLProc/Wordify main
