[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#05468a"
secondaryBackgroundColor="#d9e3ed"